title: RyuHaJin's Note
description: RyuHaJin's Note
theme: just-the-docs

url: https://ryuhajin.github.io
baseurl: ""

github:
  username: ryuhajin

nav_enabled: true

math: katex

favicon_ico: "/images/cat_yellow_bg.ico"

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: highlight
    color: yellow
  note:
    title: note
    color: purple
  important:
    title: important
    color: blue
  new:
    title: new
    color: green

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
