title: RyuHaJin's Note
description: RyuHaJin's Note
theme: just-the-docs

url: https://ryuhajin.github.io
baseurl: ""

github:
  username: ryuhajin

nav_enabled: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
